---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: qaisar-lernia-app
spec:
  lookupPolicy:
    local: true
  tags:
  - annotations: null
    from:
      kind: DockerImage
      name: ghcr.io/qaisardevops/lernia-app:latest
    importPolicy:
      importMode: Legacy
      scheduled: true
    name: latest
    referencePolicy:
      type: Source

